name: Release Please

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Release Please
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: simple
          package-name: apollo-mdm-task-pipeline
